(() => {
    "use strict";

    const EXTENSION_NAME = "RP Glass";
    const VERSION = "0.2.0";
    const ROOT_CLASS = "rp-glass-loaded";

    function markMessages() {
        document.querySelectorAll("#chat .mes").forEach((mes) => {
            mes.classList.add("rp-glass-message");

            const text = mes.querySelector(".mes_text");
            if (!text) return;

            // Scene header generated by the RP prompt: first H1 containing scene metadata.
            const firstH1 = text.querySelector(":scope > h1");
            if (firstH1 && /📅|🕒|📍|🌫/.test(firstH1.textContent || "")) {
                firstH1.classList.add("rpg-scene-header");
            }

            // Thought/meta panels. Keep markup intact; only classify for styling.
            text.querySelectorAll("details").forEach((details) => {
                const summary = details.querySelector("summary");
                const label = (summary?.textContent || "").toLowerCase();

                if (/мысл|thought|распаковать/.test(label)) {
                    details.classList.add("rpg-thoughts");
                }

                if (/независим|читател|reader/.test(label)) {
                    details.classList.add("rpg-reader");
                }
            });
        });
    }

    function observeChat() {
        const chat = document.querySelector("#chat");
        if (!chat) {
            setTimeout(observeChat, 500);
            return;
        }

        markMessages();

        const observer = new MutationObserver(() => {
            requestAnimationFrame(markMessages);
        });

        observer.observe(chat, {
            childList: true,
            subtree: true
        });
    }

    function init() {
        document.documentElement.classList.add(ROOT_CLASS);
        observeChat();
        console.log(`💜 ${EXTENSION_NAME} v${VERSION} loaded`);
    }

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", init, { once: true });
    } else {
        init();
    }
})();
